# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 211c738b5d0aa166e97a55183bc7a3676ce1fa4f6079f1c5d3c581132bcce0ba54cfd1a1fcda2d2a39c843041489174361ca1caf9f73b2cc2710955256dd8456

test:
  secret_key_base: abd07e306b8795c4b5b0b026a0f4cdd118476e0f88a3ca6160939a5d2b9533cf94855efb237b5b4301e50930257498e9633ac9e506cd8f2021871d9fda59bc4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
